services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:8080" 
    depends_on:
      - server 
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:80" 
    volumes:
      - ./server:/var/www/html  
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    networks:
      - goflow-network

networks:
  goflow-network:
    driver: bridge
